// <auto-generated />
namespace HealthyEating.Client.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class puttedvirtuals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(puttedvirtuals));
        
        string IMigrationMetadata.Id
        {
            get { return "201710182157475_puttedvirtuals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
